# FriendlyChat

use_frameworks!
platform :ios, '8.0'

pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'FirebaseUI', '~> 1.0'


target 'FriendlyChatSwift' do
end
